name: Ruff check
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  ruff:
    name: Ruff check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: astral-sh/ruff-action@v3
